### ISSUE TITLE
Can't run simulation from Touchstone file - "The number of derivatives at boundaries does not match, expected 1, got 0+0"

### ISSUE THREAD

**Issue by wolframalexa** [capn-freako/PyBERT#154]
> **Describe the bug**

Simulation will not run due to error - "the number of derivatives at boundaries does not match, expected 1, got 0+0"

**To Reproduce**
1. Go to "Interconnect" section
2. Enter path to sample.ts file (attached)
3. Ctrl + R to run simulation
4. Error appears in bottom left corner

Here is the error in the terminal:
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/pybert/threads/sim.py", line 18, in run
    my_run_simulation(self.the_pybert, aborted_sim=self.stopped)
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/pybert/models/bert.py", line 159, in my_run_simulation
    chnl_h = self.calc_chnl_h()
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/pybert/pybert.py", line 1099, in calc_chnl_h
    ch_s2p_pre = import_channel(self.ch_file, ts, f, renumber=self.renumber)
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/pybert/utility.py", line 1011, in import_channel
    h = import_time(filename, sample_per)
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/pybert/utility.py", line 1073, in import_time
    return interp_time(ts, xs, sample_per)
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/pybert/utility.py", line 1033, in interp_time
    krnl = interp1d(ts, xs, kind="cubic", bounds_error=False, fill_value=0, assume_sorted=True)
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 630, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/home/alexa/.venv/pybert6/lib/python3.10/site-packages/scipy/interpolate/_bsplines.py", line 1461, in make_interp_spline
    raise ValueError("The number of derivatives at boundaries does not "
ValueError: The number of derivatives at boundaries does not match: expected 1, got 0+0

**Expected behavior**
I expect the simulation to run.

**Screenshots**

![image](https://github.com/capn-freako/PyBERT/assets/50972270/398dff45-744c-42c2-87e4-059c29dcc8b4)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, or MacOS] Linux Ubuntu 22.04
 - Python Version [e.g. 3.7.4] 3.10.12
 - PyBERT Version [e.g. 3.3.0] 6.1.4

**Additional context**
I've attached the simple Touchstone file I generated from the [skrf Network init example](https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.network.Network.__init__.html#skrf.network.Network.__init__) as a .txt file because GitHub won't support the .ts extension.

I'm new to PyBERT so it's entirely possible I'm not setting up the simulation properly. I also understand this may not be the best place for help - if there's a better help forum that I can post on or a user guide I can read, please feel free to point me in that direction. Appreciate your time!
[sample.txt](https://github.com/user-attachments/files/15991212/sample.txt)

**Comment by wolframalexa** [comment]
Figured it out, and now I have PyBERT running a simple simulation. Some things I learned along the way, in case this helps anyone else:
* scipy has trouble interpolating if you have too few datapoints (was the issue above)
* when your frequency is too low, the vector becomes massive and your computer will run out of memory 
* If using a touchstone file, you must use the .snp extension rather than the .ts one, otherwise it is not interpreted as a Touchstone file and it expects an impulse response
