### ISSUE TITLE
PyBERT crashes during zero forcing error calculation.

### ISSUE THREAD

**Issue by capn-freako** [capn-freako/PyBERT#83]
Entering for Yoel.

**Describe the bug**
PyBERT is crashing when making the _zero forcing error approximation_ calculation.

**To Reproduce**
(Requires a particular IBIS-AMI model.)

**Expected behavior**
PyBERT doesn't crash.

**Screenshots**
Truncated backtrace:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pybert\lib\site-packages\traits\trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "C:\ProgramData\Anaconda3\envs\pybert\lib\site-packages\traits\trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "C:\ProgramData\Anaconda3\envs\pybert\lib\site-packages\traits\has_traits.py", line 1053, in wrapper0
    return function(arg)
  File "C:\ProgramData\Anaconda3\envs\pybert\lib\site-packages\traits\has_traits.py", line 3612, in notify
    self.trait_property_changed(name, old)
  File "C:\ProgramData\Anaconda3\envs\pybert\lib\site-packages\traits\has_traits.py", line 979, in decorator
    self.__dict__[name] = result = function(self)
  File "C:\ProgramData\Anaconda3\envs\pybert\lib\site-packages\pybert\pybert.py", line 1357, in _get_przf_err
    err += p[clock_pos + (i + 1) * nspui] ** 2
IndexError: index 350 is out of bounds for axis 0 with size 324

```
**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, or MacOS]
 - Python Version [e.g. 3.7.4]
 - PyBERT Version [e.g. 3.3.0]

**Additional context**
Proposed fix:

```
$ git diff pybert/pybert.py
diff --git a/pybert/pybert.py b/pybert/pybert.py
index 638a549..efdc7ad 100755
--- a/pybert/pybert.py
+++ b/pybert/pybert.py
@@ -1353,10 +1353,13 @@ class PyBERT(HasTraits):

         (clock_pos, _) = pulse_center(p, nspui)
         err = 0
+        len_p = len(p)
         for i in range(n_taps):
-            err += p[clock_pos + (i + 1) * nspui] ** 2
+            ix = clock_pos + (i + 1) * nspui
+            if ix < len_p:
+                err += p[ix]**2

-        return err / p[clock_pos] ** 2
+        return err / p[clock_pos]**2

     # Changed property handlers.
     def _status_str_changed(self):

```

**Comment by capn-freako** [comment]
Fixed by b75a6109b26
