### ISSUE TITLE
Spontaneous Crashing Under Windows 10

### ISSUE THREAD

**Issue by capn-freako** [capn-freako/PyBERT#86]
**Describe the bug**
Since moving to a new Windows 10 laptop, I've noticed PyBERT spontaneously crashing under the following conditions:

- When attempting to view the _Output_ sub-tab of the _Results_ tab.
- When running the co-optimizer.

**To Reproduce**
1. Attempt to view the _Outputs_ sub-tab of the _Results_ tab, or
2. Attempt to co-optimize.

**Expected behavior**
PyBERT doesn't crash.

**Screenshots**
(n/a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.7.6
 - PyBERT Version 3.3.2

**Additional context**
This stack trace came after a co-optimizer crash:

```
(pybert-dev) PS C:\Users\capnf\Documents\GitHub\PyBERT> python -m pybert
C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\chaco\lineplot.py:255: UserWarning: Chaco.LinePlot: len(value) 958 - len(index) 400 = 558

  % (len(value), len(index), size_diff))
Traceback (most recent call last):
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\qt4\base_window.py", line 213, in paintEvent
    self.handler.paintEvent(event)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\qt4\base_window.py", line 65, in paintEvent
    self._enable_window._paint(event)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\abstract_window.py", line 471, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\component.py", line 427, in draw
    self._draw(gc, view_bounds, mode)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\component.py", line 779, in _draw
    self._dispatch_draw(layer, gc, view_bounds, mode)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\container.py", line 258, in _dispatch_draw
    my_handler(gc, view_bounds, mode)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\container.py", line 298, in _draw_container_underlay
    self._draw_underlay(gc, view_bounds, mode)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\enable\component.py", line 887, in _draw_underlay
    underlay.overlay(self, gc, view_bounds, mode)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\chaco\grid.py", line 308, in overlay
    self._draw_component(gc, view_bounds, mode)
  File "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-dev\lib\site-packages\chaco\grid.py", line 346, in _draw_component
    ends[:,0] = self._tick_extents[:,1]
IndexError: too many indices for array
(pybert-dev) PS C:\Users\capnf\Documents\GitHub\PyBERT>
```

**Comment by capn-freako** [comment]
After tinkering w/ the code, I triggered this:

```
 "C:\Users\capnf\AppData\Local\Continuum\anaconda3\envs\pybert-devplot_len: 400
\lib\site-packages\traits\has_traits.py", line 3211, in traits
    for name in self.__dict__.keys():
RuntimeError: dictionary changed size during iteration
```

That sounds very bad. :(

**Comment by capn-freako** [comment]
Oh, wait, I think the above was due to a bogus Tx IBIS-AMI model I've recently started working with; sorry. :(
